name: Tests

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [
          {project: "virus-macrophage-sample", name: "Virus Macrophage", binary: "virus-sample"},
          {project: "physiboss-cell-lines-sample", name: "PhysiBoSS Cell Lines", binary: "PhysiBoSS_Cell_Lines"},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: ""},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: "config/Fibre_Initialisation/mymodel_initialisation.xml"},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: "config/Cell_Fibre_Mechanics/mymodel_rotating.xml"},
          {project: "template", name: "PhysiCell Template", binary: "project"},
          {project: "template_BM", name: "PhysiBoSS Template", binary: "project"},
          {project: "physiboss-tnf-model", name: "PhysiBoSS TNF model", binary: "spheroid_TNF_model"},
          {project: "physiboss-tutorial", name: "PhysiBoSS Tutorial", binary: "project", config: "config/cell_cycle/PhysiCell_settings.xml"},
          {project: "physiboss-tutorial", name: "PhysiBoSS Tutorial", binary: "project", config: "config/differentiation/PhysiCell_settings.xml"},
          {project: "physiboss-tutorial-invasion", name: "PhysiBoSS Cancer Invasion", binary: "invasion_model", config: "config/PhysiCell_settings_2D.xml"}
        ]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Build ${{ matrix.projects.name }} project 
      run: |
        make ${{ matrix.projects.project }}
        make
        
    - name: Run ${{ matrix.projects.name }} project
      run: |
        ./${{ matrix.projects.binary }} ${{ matrix.projects.config }}

  macos:
    strategy:
      matrix:
        os: [macos-12, macos-14]
        projects: [
          {project: "virus-macrophage-sample", name: "Virus Macrophage", binary: "virus-sample"},
          {project: "physiboss-cell-lines-sample", name: "PhysiBoSS Cell Lines", binary: "PhysiBoSS_Cell_Lines"},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: ""},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: "config/Fibre_Initialisation/mymodel_initialisation.xml"},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: "config/Cell_Fibre_Mechanics/mymodel_rotating.xml"},
          {project: "template", name: "PhysiCell Template", binary: "project"},
          {project: "template_BM", name: "PhysiBoSS Template", binary: "project"},
          {project: "physiboss-tnf-model", name: "PhysiBoSS TNF model", binary: "spheroid_TNF_model"},
          {project: "physiboss-tutorial", name: "PhysiBoSS Tutorial", binary: "project", config: "config/cell_cycle/PhysiCell_settings.xml"},
          {project: "physiboss-tutorial", name: "PhysiBoSS Tutorial", binary: "project", config: "config/differentiation/PhysiCell_settings.xml"},
          {project: "physiboss-tutorial-invasion", name: "PhysiBoSS Cancer Invasion", binary: "invasion_model", config: "config/PhysiCell_settings_2D.xml"}
        ]
        
    runs-on: ${{ matrix.os }}
        
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ matrix.projects.name }} project
      run: |
        make ${{ matrix.projects.project }}
        make PHYSICELL_CPP=g++-12
        
    - name: Run ${{ matrix.projects.name }} project
      run: |
        ./${{ matrix.projects.binary }} ${{ matrix.projects.config }}
   
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        projects: [
          {project: "virus-macrophage-sample", name: "Virus Macrophage", binary: "virus-sample"},
          {project: "physiboss-cell-lines-sample", name: "PhysiBoSS Cell Lines", binary: "PhysiBoSS_Cell_Lines"},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: ""},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: "config/Fibre_Initialisation/mymodel_initialisation.xml"},
          {project: "physimess-sample", name: "PhysiMeSS Sample", binary: "project", config: "config/Cell_Fibre_Mechanics/mymodel_rotating.xml"},
          {project: "template", name: "PhysiCell Template", binary: "project"},
          {project: "template_BM", name: "PhysiBoSS Template", binary: "project"},
          {project: "physiboss-tnf-model", name: "PhysiBoSS TNF model", binary: "spheroid_TNF_model"},
          {project: "physiboss-tutorial", name: "PhysiBoSS Tutorial", binary: "project", config: "config/cell_cycle/PhysiCell_settings.xml"},
          {project: "physiboss-tutorial", name: "PhysiBoSS Tutorial", binary: "project", config: "config/differentiation/PhysiCell_settings.xml"},
          {project: "physiboss-tutorial-invasion", name: "PhysiBoSS Cancer Invasion", binary: "invasion_model", config: "config/PhysiCell_settings_2D.xml"}
        ]
        
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-binutils mingw-w64-x86_64-gcc mingw-w64-x86_64-headers-git mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-lapack mingw-w64-x86_64-openblas mingw-w64-x86_64-libxml2 mingw-w64-x86_64-bzip2 mingw-w64-x86_64-python mingw-w64-x86_64-python-zstandard mingw-w64-x86_64-python-cffi make bison flex mingw-w64-x86_64-ca-certificates
    
    - name: Build ${{ matrix.projects.name }} project
      run: |
        make ${{ matrix.projects.project }}
        make
        
    - name: Run ${{ matrix.projects.name }} project
      run: |        
        .\\${{ matrix.projects.binary }}.exe ${{ matrix.projects.config }}
